// SPDX-License-Identifier: MIT
// Automatically generated by build.sh
pragma solidity >=0.5.0;
address constant ExposedBytesLib = address(0x001dc4c1cefef38a777b15aa20260a54e584b16c48);
address constant ExposedBytesUtil = address(0x001d7022f5b17d2f8b695918fb48fa1089c9f85401);
